### ISSUE TITLE
Freshly made project via rete-kit throws build error

### ISSUE THREAD

**Issue by CZ-DannyK** [retejs/rete-kit#11]
Hey,

i have just tried to make new project via rete-kit (1.4.0) with angular stack (16.1.5) and basically all plugins except non angular renderer ones and when i try to run via ng serve, i get this error:

> Error: src/app/rete/3d.ts:218:14 - error TS4111: Property 'translateY' comes from an index signature, so it must be accessed with ['translateY'].
218   gridHelper.translateY(-320);

I am not sure if is it bug, misconfiguration (like strict) or something else.

I will appreciate help

Thanks,
Daniel

**Comment by CZ-DannyK** [comment]
Ahh, ok, strange, but good to know i dont have some kind of magical bug that appear only on my end. I will try to check some info related to three.js, someone had to probably already be experiencing same.

**Comment by Ni55aN** [comment]
I believe this is a TS issue. 

Due to the lack of types, I have defined my own types for three.js:

https://github.com/retejs/rete-kit/blob/8afa5b160bfda2cce932c5a9e29b0a4ba3c31340/assets/app/stack/angular/modules/shims.d.ts#L26

It extends `Record<string, any>`, but only on Windows it requires them to be accessed with ['<key>']

**Comment by Ni55aN** [comment]
if you just need to run the project, wrap the property with `(.. as any)`

**Comment by Ni55aN** [comment]
anyway, I found the issue

**Comment by Ni55aN** [comment]
2 mins 😅

**Comment by Ni55aN** [comment]
released in 1.4.1

**Comment by CZ-DannyK** [comment]
Cool, thank you :)
